# Generated by Django 2.2.10 on 2020-07-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extrashift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('datetime', models.DateTimeField()),
                ('manager', models.CharField(choices=[('SA', 'SARGIES'), ('MA', 'MARIKA'), ('LA', 'LARA'), ('TA', 'TIGRAN')], max_length=2)),
                ('quantity', models.IntegerField(default=1)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('Lable', models.CharField(choices=[('U', 'URGENT'), ('N', 'NORMAL')], max_length=1)),
                ('language', models.CharField(choices=[('EN', 'English'), ('FA', 'Persian'), ('HY', 'Armenian'), ('RU', 'Russian'), ('AR', 'Arabic'), ('TR', 'Turkish')], max_length=2)),
            ],
        ),
    ]
