# Generated by Django 2.2.10 on 2020-08-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extrashift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrashift',
            name='manager',
            field=models.CharField(choices=[('PB', 'Pitbuz'), ('LA', 'LiveSupport'), ('SM', 'ShiftManager'), ('O', 'Other')], max_length=2),
        ),
    ]
